# Generated by Django 5.2.8 on 2025-11-15 10:35

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_renthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='renthistory',
            name='transact_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', editable=False, length=5, max_length=30, prefix='tr_', unique=True),
        ),
    ]
