# Generated by Django 5.2.8 on 2025-11-15 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_renthistory_transact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerent',
            name='rent_history',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.renthistory'),
            preserve_default=False,
        ),
    ]
