# Generated by Django 5.2.8 on 2025-11-15 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_activerent_rent_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_availability',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='activerent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
