# Generated by Django 5.2.8 on 2025-11-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_room_room_availability_alter_activerent_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activerent',
            old_name='rent_history',
            new_name='rent_transaction',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=20),
        ),
    ]
