# Generated by Django 5.2.8 on 2025-11-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_rent_history_activerent_rent_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
