# Generated by Django 5.2.8 on 2025-11-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_budget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentHistory',
            new_name='RentTransaction',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=18068),
        ),
    ]
