# Generated by Django 5.2.8 on 2025-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_renthistory_renttransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=8178),
        ),
        migrations.AlterField(
            model_name='room',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='room',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
