# Generated by Django 5.2.8 on 2025-11-25 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_customuser_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=16911),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid PH mobile number (09XXXXXXXXX or +639XXXXXXXXX).', regex='^(09\\d{9}|\\+639\\d{9})$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant')], default='Tenant', max_length=20),
        ),
    ]
