# Generated by Django 5.2.8 on 2025-11-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customuser_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=14016),
        ),
    ]
