# Generated by Django 5.2.8 on 2025-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_customuser_budget_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=5871),
        ),
    ]
