# Generated by Django 5.2.8 on 2025-11-29 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_customuser_budget_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activerent',
            name='rent_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.renttransaction'),
        ),
        migrations.AlterField(
            model_name='activerent',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
        migrations.AlterField(
            model_name='activerent',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=3137),
        ),
    ]
