# Generated by Django 5.2.8 on 2025-11-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_customuser_budget_rentpaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='activerent',
            name='email_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=7375),
        ),
    ]
