# Generated by Django 5.2.8 on 2025-12-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_activerent_email_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=4909),
        ),
    ]
