# Generated by Django 5.2.8 on 2025-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_customuser_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=2884),
        ),
    ]
