# Generated by Django 5.2.8 on 2025-12-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_customuser_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=4483),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
