# Generated by Django 5.2.8 on 2025-12-01 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_customuser_budget_delete_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=18242),
        ),
        migrations.CreateModel(
            name='LandlordApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandlordApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='landlord_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='api.landlordapplication')),
            ],
        ),
    ]
