# Generated by Django 5.2.8 on 2025-12-01 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_customuser_budget_landlordapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=7761),
        ),
    ]
