# Generated by Django 5.2.8 on 2025-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_landlordapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlordapplicantdocument',
            old_name='application_document',
            new_name='application',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=9890),
        ),
    ]
