# Generated by Django 5.2.8 on 2025-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_application_document_landlordapplicantdocument_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordapplication',
            name='document',
            field=models.FileField(default='', upload_to='landlord_docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=3695),
        ),
        migrations.DeleteModel(
            name='LandlordApplicantDocument',
        ),
    ]
