# Generated by Django 5.2.8 on 2025-12-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_landlordapplication_document_alter_customuser_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=12970),
        ),
    ]
