# Generated by Django 5.2.8 on 2025-12-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_customuser_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=9112),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Landlord', 'Landlord'), ('Tenant', 'Tenant'), ('SuperAdmin', 'SuperAdmin')], default='Tenant', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlordapplication',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
