# Generated by Django 5.2.8 on 2025-12-05 02:33

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_customuser_budget_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordapplication',
            name='application_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', editable=False, length=5, max_length=30, prefix='APL_', unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='budget',
            field=models.IntegerField(default=10753),
        ),
    ]
